### ISSUE TITLE
Merging config values for package dependencies 

### ISSUE THREAD

**Issue by ilayaperumalg** [spring-cloud/spring-cloud-skipper#112]
We need to make sure the package dependencies are merged with the appropriate config values when set via Install/Upgrade request `raw` config values.

Also, there is a type casting that sets the loading of merged config values into Map which needs to be fixed as well.

**Comment by markpollack** [comment]
I have not been able to reproduce this yet.

**Comment by markpollack** [comment]
made explicit cast check in bd5c3979d3f69fa6ab4d3b58b875cb47ac45b20a

**Comment by markpollack** [comment]
Found it again in this case

skipper:>upgrade --release-name ticktockskipper --package-name ticktock --package-version 1.0.0 --property-string log.spec.applicationProperties.log.level=INFO
Pretty print yaml to ovveride = |
  log:
      spec:
          applicationProperties:
              log:
                  level: INFO



```2017-10-12 11:56:28.731 ERROR 14348 --- [nio-7577-exec-7] o.a.c.c.C.[.[.[/].[dispatcherServlet]    : Servlet.service() for servlet [dispatcherServlet] in context with path [] threw exception [Request processing failed; nested exception is java.lang.ClassCastException: java.lang.String cannot be cast to java.util.Map] with root cause

java.lang.ClassCastException: java.lang.String cannot be cast to java.util.Map
	at org.springframework.cloud.skipper.server.service.ConfigValueUtils.mergeConfigValues(ConfigValueUtils.java:55) ~[classes!/:1.0.0.BUILD-SNAPSHOT]
	at org.springframework.cloud.skipper.server.service.ReleaseService.upgrade(ReleaseService.java:230) ~[classes!/:1.0.0.BUILD-SNAPSHOT]
	at org.springframework.cloud.skipper.server.controller.SkipperController.upgrade(SkipperController.java:123) ~[classes!/:1.0.0.BUILD-SNAPSHOT]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_131]

```

**Comment by markpollack** [comment]
Should add at least a cast check and throw an exception.
```
                // merge top level override values on top level package values
                if (StringUtils.hasText(overrideValues.getRaw())) {
                       Object data = yaml.load(overrideValues.getRaw());
                       if (data instanceof Map) {
                               Map<String, Object> overrideMap = (Map<String, Object>) yaml.load(overrideValues.getRaw());
                               mergedValues = mergeOverrideMap(pkg, overrideMap);
                       }
                       else {
                               throw new SkipperException("don't know what to do with data = " + data);
                       }
```
