### ISSUE TITLE
When deleting a release, should check to see if it's current state is not already deleted.

### ISSUE THREAD

**Issue by markpollack** [spring-cloud/spring-cloud-skipper#264]
Doing this now, results in an icky stack trace....and bad user message

```
skipper:>delete --release-name helloworld-pcf
org.springframework.web.client.HttpServerErrorException: 500 Internal Server Error
Details of the error have been omitted. You can use the stacktrace command to print the full stacktrace.
```
2017-10-24T20:45:27.61-0400 [APP/PROC/WEB/0] OUT java.lang.IllegalStateException: App helloworld-pcf-helloworld-v1 is not in a deployed state
2017-10-24T20:45:27.61-0400 [APP/PROC/WEB/0] OUT 	at org.springframework.cloud.deployer.spi.cloudfoundry.CloudFoundryAppDeployer.assertApplicationExists(CloudFoundryAppDeployer.java:171) ~[spring-cloud-deployer-cloudfoundry-1.3.0.M2.jar!/:1.3.0.M2]
2017-10-24T20:45:27.61-0400 [APP/PROC/WEB/0] OUT 	at org.springframework.cloud.deployer.spi.cloudfoundry.CloudFoundryAppDeployer.lambda$undeploy$3(CloudFoundryAppDeployer.java:151) ~[spring-cloud-deployer-cloudfoundry-1.3.0.M2.jar!/:1.3.0.M2]
```

```
2017-10-24T20:45:27.61-0400 [APP/PROC/WEB/0] OUT 		at org.springframework.cloud.skipper.server.deployer.AppDeployerReleaseManager.delete(AppDeployerReleaseManager.java:283) ~[spring-cloud-skipper-server-core-1.0.0.BUILD-SNAPSHOT.jar!/:1.0.0.BUILD-SNAPSHOT]
```

**Comment by ilayaperumalg** [comment]
For delete, it might be better to delete the release that is in `deployed` status. The only downside with that approach is the deletion can update the status of the release that is `deployed` and it may not be the latest entry in the history.

Following explains this scenario:

```
skipper:>install --release-name test1 --package-name log --package-version 1.0.0
Released test1
skipper:>upgrade --release-name test1 --package-name log --package-version 1.1.0 
test1 has been upgraded.
Last Deployed: Thu Oct 26 16:12:34 IST 2017

skipper:>history --release-name test1
╔═══════╤════════╤════════╤═══════╤═══════╤═══════════╗
║Version│  Last  │ Status │Package│Package│Description║
║       │updated │        │ Name  │Version│           ║
╠═══════╪════════╪════════╪═══════╪═══════╪═══════════╣
║2      │Thu Oct │FAILED  │log    │1.1.0  │Did not    ║
║       │26      │        │       │       │detect apps║
║       │16:12:34│        │       │       │in         ║
║       │IST 2017│        │       │       │repalcing  ║
║       │        │        │       │       │release as ║
║       │        │        │       │       │healthy    ║
║       │        │        │       │       │after 5000 ║
║       │        │        │       │       │ms.        ║
║1      │Thu Oct │DEPLOYED│log    │1.0.0  │Install    ║
║       │26      │        │       │       │complete   ║
║       │16:12:00│        │       │       │           ║
║       │IST 2017│        │       │       │           ║
╚═══════╧════════╧════════╧═══════╧═══════╧═══════════╝

skipper:>delete --release-name test1
test1 has been deleted.

skipper:>history --release-name test1
╔═══════╤════════╤═══════╤═══════╤═══════╤═══════════╗
║Version│  Last  │Status │Package│Package│Description║
║       │updated │       │ Name  │Version│           ║
╠═══════╪════════╪═══════╪═══════╪═══════╪═══════════╣
║2      │Thu Oct │FAILED │log    │1.1.0  │Did not    ║
║       │26      │       │       │       │detect apps║
║       │16:12:34│       │       │       │in         ║
║       │IST 2017│       │       │       │repalcing  ║
║       │        │       │       │       │release as ║
║       │        │       │       │       │healthy    ║
║       │        │       │       │       │after 5000 ║
║       │        │       │       │       │ms.        ║
║1      │Thu Oct │DELETED│log    │1.0.0  │Delete     ║
║       │26      │       │       │       │complete   ║
║       │16:12:00│       │       │       │           ║
║       │IST 2017│       │       │       │           ║
╚═══════╧════════╧═══════╧═══════╧═══════╧═══════════╝

skipper:>delete --release-name test1
org.springframework.cloud.skipper.ReleaseNotFoundException: Release with the name [test1] doesn't exist
Details of the error have been omitted. You can use the stacktrace command to print the full stacktrace.
```
