### ISSUE TITLE
Installing helloworld:1.0.1, then upgrading to helloworld:1.0.0 and then trying to rollback does not work

### ISSUE THREAD

**Issue by donovanmuller** [spring-cloud/spring-cloud-skipper#349]
On HEAD 9a1716f8e9f7e80c9d371869f602fea95ef493ad

I installed the `helloworld` package (latest version is `1.0.1`) successfully, then "upgraded"  to `helloworld:1.0.0` but when trying to rollback to the initial release version (using `1.0.1`) I get:

```console
org.springframework.cloud.skipper.ReleaseNotFoundException: Release with the name [hello-1] doesn't exist
```

Steps to reproduce:

```console
# Install initial release
skipper:>install --package-name helloworld --release-name hello-1
Released hello-1. Now at version v1.
skipper:>status --release-name hello-1
╔═══════════════╤═══════════════════════════════════════════════════════════════════╗
║Last Deployed  │Sun Nov 19 07:03:17 SAST 2017                                      ║
║Status         │DEPLOYED                                                           ║
║Platform Status│All applications have been successfully deployed.                  ║
║               │[hello-1.helloworld-v1], State = [hello-1.helloworld-v1-0=deployed]║
╚═══════════════╧═══════════════════════════════════════════════════════════════════╝

# Now "upgrade" to 1.0.0 version of package
skipper:>upgrade --release-name hello-1 --package-name helloworld --package-version 1.0.0
hello-1 has been upgraded.  Now at version v2.
skipper:>status --release-name hello-1
╔═══════════════╤═══════════════════════════════════════════════════════════════════╗
║Last Deployed  │Sun Nov 19 07:06:26 SAST 2017                                      ║
║Status         │UNKNOWN                                                            ║
║Platform Status│All applications have been successfully deployed.                  ║
║               │[hello-1.helloworld-v2], State = [hello-1.helloworld-v2-0=deployed]║
╚═══════════════╧═══════════════════════════════════════════════════════════════════╝
```

note the `Status` of `UNKNOWN` even though app is deployed.
This is probably what prevents the rollback I assume.

```console
skipper:>history --release-name hello-1
╔═══════╤═════════════════════════════╤════════╤════════════╤═══════════════╤════════════════════════╗
║Version│        Last updated         │ Status │Package Name│Package Version│      Description       ║
╠═══════╪═════════════════════════════╪════════╪════════════╪═══════════════╪════════════════════════╣
║2      │Sun Nov 19 07:06:26 SAST 2017│UNKNOWN │helloworld  │1.0.0          │Upgrade install underway║
║1      │Sun Nov 19 07:03:17 SAST 2017│DEPLOYED│helloworld  │1.0.1          │Install complete        ║
╚═══════╧═════════════════════════════╧════════╧════════════╧═══════════════╧════════════════════════╝

# Try rollback
skipper:>rollback --release-name hello-1
org.springframework.cloud.skipper.ReleaseNotFoundException: Release with the name [hello-1] doesn't exist
Details of the error have been omitted. You can use the stacktrace command to print the full stacktrace.
skipper:>stacktrace
org.springframework.cloud.skipper.ReleaseNotFoundException: Release with the name [hello-1] doesn't exist
	at org.springframework.cloud.skipper.client.SkipperClientResponseErrorHandler.handleReleaseNotFoundException(SkipperClientResponseErrorHandler.java:92)
	at org.springframework.cloud.skipper.client.SkipperClientResponseErrorHandler.handleError(SkipperClientResponseErrorHandler.java:69)
```

Server logs below for reference:

```console
 Nov 19 07:25:02 SAST 2017]; root of context hierarchy
2017-11-19 07:25:03.118  INFO 9896 --- [           main] trationDelegate$BeanPostProcessorChecker : Bean 'configurationPropertiesRebinderAutoConfiguration' of type [org.springframework.cloud.autoconfigure.ConfigurationPropertiesRebinderAutoConfiguration$$EnhancerBySpringCGLIB$$ee548169] is not eligible for getting processed by all BeanPostProcessors (for example: not eligible for auto-proxying)
2017-11-19 07:25:03.662  INFO 9896 --- [           main] c.c.c.ConfigServicePropertySourceLocator : Fetching config from server at: http://localhost:8888
2017-11-19 07:25:03.767  WARN 9896 --- [           main] c.c.c.ConfigServicePropertySourceLocator : Could not locate PropertySource: I/O error on GET request for "http://localhost:8888/application/default": Connection refused (Connection refused); nested exception is java.net.ConnectException: Connection refused (Connection refused)
2017-11-19 07:25:03.769  INFO 9896 --- [           main] o.s.c.s.s.app.SkipperServerApplication   : No active profile set, falling back to default profiles: default
2017-11-19 07:25:04.919  INFO 9896 --- [           main] o.s.cloud.context.scope.GenericScope     : BeanFactory id=8cf25de1-dd57-374c-98ea-ec2da86b23ee
2017-11-19 07:25:05.138  INFO 9896 --- [           main] o.s.s.concurrent.ThreadPoolTaskExecutor  : Initializing ExecutorService  'skipperThreadPoolTaskExecutor'
2017-11-19 07:25:05.518  INFO 9896 --- [           main] s.b.c.e.t.TomcatEmbeddedServletContainer : Tomcat initialized with port(s): 7577 (http)
2017-11-19 07:25:05.530  INFO 9896 --- [           main] o.apache.catalina.core.StandardService   : Starting service Tomcat
2017-11-19 07:25:05.531  INFO 9896 --- [           main] org.apache.catalina.core.StandardEngine  : Starting Servlet Engine: Apache Tomcat/8.5.14
2017-11-19 07:25:05.618  INFO 9896 --- [ost-startStop-1] o.a.c.c.C.[Tomcat].[localhost].[/]       : Initializing Spring embedded WebApplicationContext
2017-11-19 07:25:06.442  INFO 9896 --- [           main] j.LocalContainerEntityManagerFactoryBean : Building JPA container EntityManagerFactory for persistence unit 'default'
2017-11-19 07:25:07.488  INFO 9896 --- [           main] j.LocalContainerEntityManagerFactoryBean : Initialized JPA EntityManagerFactory for persistence unit 'default'
2017-11-19 07:25:09.706  INFO 9896 --- [           main] o.s.c.s.s.s.ReleaseStateUpdateService    : Setting up ReleaseStateUpdateService
2017-11-19 07:25:10.057  INFO 9896 --- [           main] s.a.ScheduledAnnotationBeanPostProcessor : No TaskScheduler/ScheduledExecutorService bean found for scheduled processing
2017-11-19 07:25:10.114  INFO 9896 --- [           main] s.b.c.e.t.TomcatEmbeddedServletContainer : Tomcat started on port(s): 7577 (http)
2017-11-19 07:25:10.176  INFO 9896 --- [           main] .s.c.s.s.s.DeployerInitializationService : Added Local Deployer account named 'default' into Deployer Repository.
2017-11-19 07:25:10.326  INFO 9896 --- [           main] .c.s.s.s.RepositoryInitializationService : Initializing repository database with Repository{name='experimental', url='http://skipper-repository.cfapps.io/repository/experimental', local=false}
2017-11-19 07:25:10.379  INFO 9896 --- [           main] .c.s.s.s.RepositoryInitializationService : Initializing repository database with Repository{name='local', url='http://192.168.0.10:7577', local=true}
2017-11-19 07:25:11.312  INFO 9896 --- [           main] o.s.c.s.s.s.PackageMetadataService       : Downloading package metadata from URL [http://skipper-repository.cfapps.io/repository/experimental/index.yml]
2017-11-19 07:25:11.653  INFO 9896 --- [           main] o.s.c.s.s.app.SkipperServerApplication   : Started SkipperServerApplication in 9.311 seconds (JVM running for 9.744)
2017-11-19 07:25:17.991  INFO 9896 --- [nio-7577-exec-1] o.a.c.c.C.[Tomcat].[localhost].[/]       : Initializing Spring FrameworkServlet 'dispatcherServlet'
2017-11-19 07:25:32.728  INFO 9896 --- [nio-7577-exec-2] o.s.c.d.r.s.LRUCleaningResourceLoader    : Free Disk Space = 13.05%, Target Free Space >25.00%
2017-11-19 07:25:32.749  INFO 9896 --- [nio-7577-exec-2] o.s.c.d.spi.local.LocalAppDeployer       : Deploying app with deploymentId hello-1.helloworld-v1 instance 0.
   Logs will be in /var/folders/79/c5g_bfkn74d_155b5cpl39q40000gn/T/spring-cloud-dataflow-2938300608460679826/hello-1-1511069132731/hello-1.helloworld-v1
2017-11-19 07:26:00.885  INFO 9896 --- [nio-7577-exec-4] o.s.c.s.server.deployer.ReleaseAnalyzer  : Existing Package and Upgrade Package both have no dependent packages.
2017-11-19 07:26:00.885  INFO 9896 --- [nio-7577-exec-4] o.s.c.s.server.deployer.ReleaseAnalyzer  : Differences detected, upgrading app helloworld
2017-11-19 07:26:00.900  INFO 9896 --- [nio-7577-exec-4] o.s.c.s.s.d.AppDeployerReleaseManager    : Difference report for upgrade of release hello-1
2017-11-19 07:26:00.900  INFO 9896 --- [nio-7577-exec-4] o.s.c.s.s.d.AppDeployerReleaseManager    : Existing resource =[maven://org.springframework.cloud.samples:spring-cloud-skipper-samples-helloworld:1.0.1.RELEASE], Replacing name=[maven://org.springframework.cloud.samples:spring-cloud-skipper-samples-helloworld:1.0.0.RELEASE]
2017-11-19 07:26:00.913  INFO 9896 --- [  StateUpdate-1] o.s.c.d.r.s.LRUCleaningResourceLoader    : Free Disk Space = 13.06%, Target Free Space >25.00%
2017-11-19 07:26:00.914  INFO 9896 --- [  StateUpdate-1] o.s.c.d.r.s.LRUCleaningResourceLoader    : [SUCCESS] Deleting /Users/donovan/.m2/repository/org/springframework/cloud/samples/spring-cloud-skipper-samples-helloworld/1.0.1.RELEASE/spring-cloud-skipper-samples-helloworld-1.0.1.RELEASE.jar parent directory to regain free disk space.
2017-11-19 07:26:00.921  INFO 9896 --- [  StateUpdate-1] o.s.c.d.spi.local.LocalAppDeployer       : Deploying app with deploymentId hello-1.helloworld-v2 instance 0.
   Logs will be in /var/folders/79/c5g_bfkn74d_155b5cpl39q40000gn/T/spring-cloud-dataflow-2938300608460679826/hello-1-1511069160915/hello-1.helloworld-v2
2017-11-19 07:26:00.931  INFO 9896 --- [  StateUpdate-1] o.s.c.s.s.d.strategies.HealthCheckStep   : Waiting for apps in release hello-1-v2 to be healthy.
2017-11-19 07:26:05.947  INFO 9896 --- [  StateUpdate-1] o.s.c.s.s.d.s.HandleHealthCheckStep      : Release hello-1-v2 has been DEPLOYED
2017-11-19 07:26:05.947  INFO 9896 --- [  StateUpdate-1] o.s.c.s.s.d.s.HandleHealthCheckStep      : Apps in release hello-1-v2 are healthy.
2017-11-19 07:26:05.948  INFO 9896 --- [  StateUpdate-1] o.s.c.s.s.d.s.HandleHealthCheckStep      : Deleting changed applications from existing release hello-1-v1
2017-11-19 07:26:05.950  INFO 9896 --- [  StateUpdate-1] o.s.c.d.spi.local.LocalAppDeployer       : Un-deploying app with deploymentId hello-1.helloworld-v1 instance 0.
```

**Comment by ilayaperumalg** [comment]
Hi @donovanmuller Yes, that's because your upgrade is still underway and hasn't completed. The only successful operation right before you issue the `rollback` command was the `deploy` of `helloworld-1.0.1` and this is still running. Hence, you don't have to rollback to `helloworld-1.0.1` which is already running. 

We plan to provide better message description when responding to the `rollback` command.

This also brought up one other case where you `delete` the upgrade release which is `UNKNOWN` and perform `rollback`, though it is expected to run the `rollback` to `helloworld-1.0.1` it is not needed as `helloworld-1.0.1` is already running. Would need to try that.

**Comment by donovanmuller** [comment]
The real issue for me, was why the status of version 2 of the release was `UNKNOWN` when the app had deployed successfully?

```console
# From above (issue description) after "upgrading"
skipper:>status --release-name hello-1
╔═══════════════╤═══════════════════════════════════════════════════════════════════╗
║Last Deployed  │Sun Nov 19 07:06:26 SAST 2017                                      ║
║Status         │UNKNOWN                                                            ║
║Platform Status│All applications have been successfully deployed.                  ║
║               │[hello-1.helloworld-v2], State = [hello-1.helloworld-v2-0=deployed]║
╚═══════════════╧═══════════════════════════════════════════════════════════════════╝
```

The app's health check passes and is healthy by all counts.
Deployment and health check confirmed in the server logs:

```console
...
2017-11-19 07:26:00.921  INFO 9896 --- [  StateUpdate-1] o.s.c.d.spi.local.LocalAppDeployer       : Deploying app with deploymentId hello-1.helloworld-v2 instance 0.
   Logs will be in /var/folders/79/c5g_bfkn74d_155b5cpl39q40000gn/T/spring-cloud-dataflow-2938300608460679826/hello-1-1511069160915/hello-1.helloworld-v2
2017-11-19 07:26:00.931  INFO 9896 --- [  StateUpdate-1] o.s.c.s.s.d.strategies.HealthCheckStep   : Waiting for apps in release hello-1-v2 to be healthy.
2017-11-19 07:26:05.947  INFO 9896 --- [  StateUpdate-1] o.s.c.s.s.d.s.HandleHealthCheckStep      : Release hello-1-v2 has been DEPLOYED
2017-11-19 07:26:05.947  INFO 9896 --- [  StateUpdate-1] o.s.c.s.s.d.s.HandleHealthCheckStep      : Apps in release hello-1-v2 are healthy.
2017-11-19 07:26:05.948  INFO 9896 --- [  StateUpdate-1] o.s.c.s.s.d.s.HandleHealthCheckStep      : Deleting changed applications from existing release hello-1-v1
2017-11-19 07:26:05.950  INFO 9896 --- [  StateUpdate-1] o.s.c.d.spi.local.LocalAppDeployer       : Un-deploying app with deploymentId hello-1.helloworld-v1 instance 0.
```

Therefore, my assumption given the above successful install of `helloworld:1.0.0` (release version 2) would be that version 2's status would be `DEPLOYED` as it should have completed and that version 1's status would be `DELETED`.

```console
skipper:>history --release-name hello-1
╔═══════╤═════════════════════════════╤════════╤════════════╤═══════════════╤════════════════════════╗
║Version│        Last updated         │ Status │Package Name│Package Version│      Description       ║
╠═══════╪═════════════════════════════╪════════╪════════════╪═══════════════╪════════════════════════╣
║2      │Sun Nov 19 07:06:26 SAST 2017│UNKNOWN │helloworld  │1.0.0          │Upgrade install underway║
║1      │Sun Nov 19 07:03:17 SAST 2017│DEPLOYED│helloworld  │1.0.1          │Install complete        ║
╚═══════╧═════════════════════════════╧════════╧════════════╧═══════════════╧════════════════════════╝
```

Instead the status of version 2 is `UNKNOWN` and the description of `Upgrade install underway` is misleading because it has deployed successfully and should be completed.

Am I misunderstanding something?

**Comment by ilayaperumalg** [comment]
I didn't realize your upgrade was successfully deployed in this case. This looks like a bug.

**Comment by ilayaperumalg** [comment]
@donovanmuller  From your log:

```
2017-11-19 07:26:05.947  INFO 9896 --- [  StateUpdate-1] o.s.c.s.s.d.s.HandleHealthCheckStep      : Release hello-1-v2 has been DEPLOYED
```
This means the corresponding DB update to set the status to `DEPLOYED` is expected to happen. Looks like DB update didn't go through fine. Are you running an embedded DB or external DB? Also, are you on the latest master or M1 and, are you able to see this behavior consistently?

**Comment by donovanmuller** [comment]
I'm on commit https://github.com/spring-cloud/spring-cloud-skipper/commit/9a1716f8e9f7e80c9d371869f602fea95ef493ad from `master`.

Running stock standard H2.
I.e. what you would get with `git clone ... && mvn install && java -jar ...server/target/spring-cloud-skipper-server-1.0.0.BUILD-SNAPSHOT.jar`

Behaviour is consistently reproducible.

**Comment by ilayaperumalg** [comment]
Weird. The message `Release hello-1-v2 has been DEPLOYED` is logged only after updating the release status to `DEPLOYED` as per [this](https://github.com/spring-cloud/spring-cloud-skipper/blob/master/spring-cloud-skipper-server-core/src/main/java/org/springframework/cloud/skipper/server/deployer/strategies/HandleHealthCheckStep.java#L86). It is very interesting that in your case, the DB update doesn't happen and stays in `UNKNOWN`. 

I tried a few times in my local and could see the upgrade going successfully:
```
skipper:>install --package-name helloworld --release-name hello-1
Released hello-1. Now at version v1.
skipper:>status --release-name hello-1
╔═══════════════╤════════════════════════════════════════════════════════════════════╗
║Last Deployed  │Mon Nov 20 13:01:42 IST 2017                                        ║
║Status         │DEPLOYED                                                            ║
║Platform Status│The applications are being deployed.                                ║
║               │[hello-1.helloworld-v1], State = [hello-1.helloworld-v1-0=deploying]║
╚═══════════════╧════════════════════════════════════════════════════════════════════╝

skipper:>status --release-name hello-1
╔═══════════════╤═══════════════════════════════════════════════════════════════════╗
║Last Deployed  │Mon Nov 20 13:01:42 IST 2017                                       ║
║Status         │DEPLOYED                                                           ║
║Platform Status│All applications have been successfully deployed.                  ║
║               │[hello-1.helloworld-v1], State = [hello-1.helloworld-v1-0=deployed]║
╚═══════════════╧═══════════════════════════════════════════════════════════════════╝

skipper:>upgrade --release-name hello-1 --package-name helloworld --package-version 1.0.0
hello-1 has been upgraded.  Now at version v2.
skipper:>status --release-name hello-1
╔═══════════════╤═══════════════════════════════════════════════════════════════════╗
║Last Deployed  │Mon Nov 20 13:02:41 IST 2017                                       ║
║Status         │DEPLOYED                                                           ║
║Platform Status│All applications have been successfully deployed.                  ║
║               │[hello-1.helloworld-v2], State = [hello-1.helloworld-v2-0=deployed]║
╚═══════════════╧═══════════════════════════════════════════════════════════════════╝

```

**Comment by donovanmuller** [comment]
Just tried it now again:

1. `cd /tmp && git clone https://github.com/spring-cloud/spring-cloud-skipper.git && cd spring-cloud-skipper`
2. `mvn clean install -DskipTests`
3. `java -jar spring-cloud-skipper-server/target/spring-cloud-skipper-server-1.0.0.BUILD-SNAPSHOT.jar`
4. (In another tab) ` java -jar spring-cloud-skipper-shell/target/spring-cloud-skipper-shell-1.0.0.BUILD-SNAPSHOT.jar`
5. Run through your commands [above](https://github.com/spring-cloud/spring-cloud-skipper/issues/349#issuecomment-345616131) and exactly the same as per issue description:

```console
...
2017-11-20 12:01:33.529  INFO 54846 --- [           main] o.s.c.s.s.app.SkipperServerApplication   : Started SkipperServerApplication in 11.27 seconds (JVM running for 11.73)
2017-11-20 12:01:41.260  INFO 54846 --- [nio-7577-exec-1] o.a.c.c.C.[Tomcat].[localhost].[/]       : Initializing Spring FrameworkServlet 'dispatcherServlet'
2017-11-20 12:02:06.876  INFO 54846 --- [nio-7577-exec-2] o.s.c.d.r.s.LRUCleaningResourceLoader    : Free Disk Space = 9.91%, Target Free Space >25.00%
2017-11-20 12:02:06.899  INFO 54846 --- [nio-7577-exec-2] o.s.c.d.spi.local.LocalAppDeployer       : Deploying app with deploymentId hello-1.helloworld-v1 instance 0.
   Logs will be in /var/folders/79/c5g_bfkn74d_155b5cpl39q40000gn/T/spring-cloud-dataflow-9085651201596151914/hello-1-1511172126879/hello-1.helloworld-v1
2017-11-20 12:02:27.272  INFO 54846 --- [nio-7577-exec-5] o.s.c.s.server.deployer.ReleaseAnalyzer  : Existing Package and Upgrade Package both have no dependent packages.
2017-11-20 12:02:27.272  INFO 54846 --- [nio-7577-exec-5] o.s.c.s.server.deployer.ReleaseAnalyzer  : Differences detected, upgrading app helloworld
2017-11-20 12:02:27.287  INFO 54846 --- [nio-7577-exec-5] o.s.c.s.s.d.AppDeployerReleaseManager    : Difference report for upgrade of release hello-1
2017-11-20 12:02:27.287  INFO 54846 --- [nio-7577-exec-5] o.s.c.s.s.d.AppDeployerReleaseManager    : Existing resource =[maven://org.springframework.cloud.samples:spring-cloud-skipper-samples-helloworld:1.0.1.RELEASE], Replacing name=[maven://org.springframework.cloud.samples:spring-cloud-skipper-samples-helloworld:1.0.0.RELEASE]
2017-11-20 12:02:27.304  INFO 54846 --- [  StateUpdate-1] o.s.c.d.r.s.LRUCleaningResourceLoader    : Free Disk Space = 9.92%, Target Free Space >25.00%
2017-11-20 12:02:27.305  INFO 54846 --- [  StateUpdate-1] o.s.c.d.r.s.LRUCleaningResourceLoader    : [SUCCESS] Deleting /Users/donovan/.m2/repository/org/springframework/cloud/samples/spring-cloud-skipper-samples-helloworld/1.0.1.RELEASE/spring-cloud-skipper-samples-helloworld-1.0.1.RELEASE.jar parent directory to regain free disk space.
2017-11-20 12:02:27.320  INFO 54846 --- [  StateUpdate-1] o.s.c.d.spi.local.LocalAppDeployer       : Deploying app with deploymentId hello-1.helloworld-v2 instance 0.
   Logs will be in /var/folders/79/c5g_bfkn74d_155b5cpl39q40000gn/T/spring-cloud-dataflow-9085651201596151914/hello-1-1511172147305/hello-1.helloworld-v2
2017-11-20 12:02:27.332  INFO 54846 --- [  StateUpdate-1] o.s.c.s.s.d.strategies.HealthCheckStep   : Waiting for apps in release hello-1-v2 to be healthy.
2017-11-20 12:02:32.345  INFO 54846 --- [  StateUpdate-1] o.s.c.s.s.d.s.HandleHealthCheckStep      : Release hello-1-v2 has been DEPLOYED
2017-11-20 12:02:32.346  INFO 54846 --- [  StateUpdate-1] o.s.c.s.s.d.s.HandleHealthCheckStep      : Apps in release hello-1-v2 are healthy.
2017-11-20 12:02:32.347  INFO 54846 --- [  StateUpdate-1] o.s.c.s.s.d.s.HandleHealthCheckStep      : Deleting changed applications from existing release hello-1-v1
2017-11-20 12:02:32.349  INFO 54846 --- [  StateUpdate-1] o.s.c.d.spi.local.LocalAppDeployer       : Un-deploying app with deploymentId hello-1.helloworld-v1 instance 0.
```

```console
skipper:>status --release-name hello-1
╔═══════════════╤═══════════════════════════════════════════════════════════════════╗
║Last Deployed  │Mon Nov 20 12:02:27 SAST 2017                                      ║
║Status         │UNKNOWN                                                            ║
║Platform Status│All applications have been successfully deployed.                  ║
║               │[hello-1.helloworld-v2], State = [hello-1.helloworld-v2-0=deployed]║
╚═══════════════╧═══════════════════════════════════════════════════════════════════╝

skipper:>history --release-name hello-1
╔═══════╤═════════════════════════════╤════════╤════════════╤═══════════════╤════════════════════════╗
║Version│        Last updated         │ Status │Package Name│Package Version│      Description       ║
╠═══════╪═════════════════════════════╪════════╪════════════╪═══════════════╪════════════════════════╣
║2      │Mon Nov 20 12:02:27 SAST 2017│UNKNOWN │helloworld  │1.0.0          │Upgrade install underway║
║1      │Mon Nov 20 12:01:56 SAST 2017│DEPLOYED│helloworld  │1.0.1          │Install complete        ║
╚═══════╧═════════════════════════════╧════════╧════════════╧═══════════════╧════════════════════════╝
```

¯\\_(ツ)_/¯

**Comment by sabbyanandan** [comment]
FWIW, I repeated [this](https://github.com/spring-cloud/spring-cloud-skipper/issues/349#issuecomment-345649650) and [this](https://github.com/spring-cloud/spring-cloud-skipper/issues/349#issuecomment-345616131) in entirety and I see the following on master (`8c965a4`).

```
skipper:>history --release-name hello
╔═══════╤════════════════════════════╤════════╤════════════╤═══════════════╤════════════════╗
║Version│        Last updated        │ Status │Package Name│Package Version│  Description   ║
╠═══════╪════════════════════════════╪════════╪════════════╪═══════════════╪════════════════╣
║2      │Mon Nov 20 08:46:06 PST 2017│DEPLOYED│helloworld  │1.0.0          │Upgrade complete║
║1      │Mon Nov 20 08:45:04 PST 2017│DELETED │helloworld  │1.0.1          │Delete complete ║
╚═══════╧════════════════════════════╧════════╧════════════╧═══════════════╧════════════════╝
```

Hi, @donovanmuller: Please give it a go with the latest commits once again?

**Comment by donovanmuller** [comment]
@sabbyanandan just tried on 1e25bd1204ce04e5c7027fb2fa89f2cb03498763 and got the same thing.

However, I found what the issue is, at least on my machine.
Turns out undeploying version 1 (`1.0.1`) never succeeded and it was still running.

```console
$ jps
59682 spring-cloud-skipper-samples-helloworld-1.0.1.RELEASE.jar
59636 spring-cloud-skipper-server-1.0.0.BUILD-SNAPSHOT.jar
57831 Launcher
60039 Jps
32634
59674 spring-cloud-skipper-shell-1.0.0.BUILD-SNAPSHOT.jar
59693 spring-cloud-skipper-samples-helloworld-1.0.0.RELEASE.jar
```

So both versions were still running.
I killed version 1 and the status of version 2 changed to what I expected:

```console
skipper:>status --release-name hello-1
╔═══════════════╤═══════════════════════════════════════════════════════════════════╗
║Last Deployed  │Mon Nov 20 19:03:02 SAST 2017                                      ║
║Status         │UNKNOWN                                                            ║
║Platform Status│All applications have been successfully deployed.                  ║
║               │[hello-1.helloworld-v2], State = [hello-1.helloworld-v2-0=deployed]║
╚═══════════════╧═══════════════════════════════════════════════════════════════════╝

---

$ kill 59682

---

skipper:>status --release-name hello-1
╔═══════════════╤═══════════════════════════════════════════════════════════════════╗
║Last Deployed  │Mon Nov 20 19:03:02 SAST 2017                                      ║
║Status         │DEPLOYED                                                           ║
║Platform Status│All applications have been successfully deployed.                  ║
║               │[hello-1.helloworld-v2], State = [hello-1.helloworld-v2-0=deployed]║
╚═══════════════╧═══════════════════════════════════════════════════════════════════╝
```

The local deployer is failing to undeploy the app on my machine for some reason and it only happens during an upgrade. Deleting a release explicitly does terminate the app.

I'll try and see what's going on... Seems to be a local issue so closing this.
