### ISSUE TITLE
Handle generic RuntimeException

### ISSUE THREAD

**Issue by markpollack** [spring-cloud/spring-cloud-skipper#370]
```2017-12-05 15:28:10.327 ERROR 15862 --- [nio-7577-exec-7] o.a.c.c.C.[.[.[/].[dispatcherServlet]    : Servlet.service() for servlet [dispatcherServlet] in context with path [] threw exception [Request processing failed; nested exception is java.lang.IllegalStateException: App 'helloworldk8s-helloworld-docker-v1' is not deployed] with root cause

java.lang.IllegalStateException: App 'helloworldk8s-helloworld-docker-v1' is not deployed
	at org.springframework.cloud.deployer.spi.kubernetes.KubernetesAppDeployer.undeploy(KubernetesAppDeployer.java:137) ~[spring-cloud-deployer-kubernetes-1.2.2.RELEASE.jar!/:1.2.2.RELEASE]
	at org.springframework.cloud.skipper.server.deployer.AppDeployerReleaseManager.delete(AppDeployerReleaseManager.java:322) ~[spring-cloud-skipper-server-core-1.0.0.BUILD-SNAPSHOT.jar!/:1.0.0.BUILD-SNAPSHOT]
```

The exception is not propagated to the client.

This is caused by not handling generic `RuntimeException` and its siblings.

**Comment by jvalkeal** [comment]
Superseded by #588
