### ISSUE TITLE
Issue updating release

### ISSUE THREAD

**Issue by mv78** [spring-cloud/spring-cloud-skipper#622]
2018-05-15 23:28:16.351 ERROR 1 --- [nio-7577-exec-2] o.a.c.c.C.[.[.[/].[dispatcherServlet]    : Servlet.service() for servlet [dispatcherServlet] in context with path [] threw exception [Request processing failed; nested exception is org.springframework.statemachine.StateMachineException: Unable to read context from store; nested exception is com.esotericsoftware.kryo.KryoException: Unable to find class: org.springframework.cloud.skipper.domain.PackageFile_$$_jvstd8e_1
Serialization trace:
packageFile (org.springframework.cloud.skipper.domain.PackageMetadata)
metadata (org.springframework.cloud.skipper.domain.Package)
pkg (org.springframework.cloud.skipper.domain.Release)] with root cause
 java.lang.ClassNotFoundException: org.springframework.cloud.skipper.domain.PackageFile_$$_jvstd8e_1
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381) ~[na:1.8.0_111-internal]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424) ~[na:1.8.0_111-internal]
	at org.springframework.boot.loader.LaunchedURLClassLoader.loadClass(LaunchedURLClassLoader.java:94) ~[spring-cloud-skipper-server.jar:1.0.4.RELEASE]

**Comment by sabbyanandan** [comment]
Is this related to https://github.com/spring-cloud/spring-cloud-dataflow/issues/2211 or something different? More details on this issue would be useful, too.

**Comment by jvalkeal** [comment]
You need to tell skipper version as at least one issue related to that error got fixed some time ago. 1.0.3 and 1.0.4 should work.

**Comment by mv78** [comment]
I updated my version to 1.0.4 and had previoise releases installed.

**Comment by sabbyanandan** [comment]
@mv78: Can you retry this on 1.0.5?

**Comment by sabbyanandan** [comment]
Closing this due to no activity.
