### ISSUE TITLE
Shell repo add/delete commands broken

### ISSUE THREAD

**Issue by jvalkeal** [spring-cloud/spring-cloud-skipper#632]
Some issues with these commands
```
skipper:>repo delete --name xxxx
404 
Details of the error have been omitted. You can use the stacktrace command to print the full stacktrace.
skipper:>stacktrace 
org.springframework.web.client.HttpClientErrorException: 404 
	at org.springframework.web.client.DefaultResponseErrorHandler.handleError(DefaultResponseErrorHandler.java:85)
	at org.springframework.cloud.skipper.client.SkipperClientResponseErrorHandler.handleError(SkipperClientResponseErrorHandler.java:78)
```

**Comment by ilayaperumalg** [comment]
It looks like the REST repository for Skipper `Repository` doesn't expose the `save` and `delete` method invocations as per [this](https://github.com/spring-cloud/spring-cloud-skipper/blob/master/spring-cloud-skipper-server-core/src/main/java/org/springframework/cloud/skipper/server/repository/RepositoryRepository.java#L51).

I think we had a reason not to expose these endpoints as we wanted to avoid user deleting the default `local` repository etc., Perhaps, we can add some check and allow these methods to be exposed?

What do you think @jvalkeal @markpollack ?

**Comment by markpollack** [comment]
As I recall, I purposely left this not exposed and thought that whoever started the skipper server would edit the yaml file.  I suppose the right way is to add a role to that endpoint.  Can we push this off to a backport targeting 1.0.6 so we can go ahead with the overdue scdf 1.5.1 release?

**Comment by markpollack** [comment]
maybe remove the command or just log a more decent warning?

**Comment by sabbyanandan** [comment]
We will revisit it in the context of RBAC in future.
