### ISSUE TITLE
Uploading package with wrong path results awkward error

### ISSUE THREAD

**Issue by jvalkeal** [spring-cloud/spring-cloud-skipper#667]
```
skipper:>package upload --repo-name local --path /home/jvalkealahti/work/skipper/cfapps/jannelogcf-1.0.0.zip
/home/jvalkealahti/work/skipper/cfapps/jannelogcf-1.0.0.zip
Details of the error have been omitted. You can use the stacktrace command to print the full stacktrace.
skipper:>stacktrace 
java.lang.IllegalArgumentException: /home/jvalkealahti/work/skipper/cfapps/jannelogcf-1.0.0.zip
	at org.springframework.cloud.skipper.shell.command.PackageCommands.upload(PackageCommands.java:131)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
```
At minimum we should really have real error

**Comment by sabbyanandan** [comment]
Closing this in favor of #675.
