### ISSUE TITLE
Handle the case of apps deleted outside of Skipper

### ISSUE THREAD

**Issue by sabbyanandan** [spring-cloud/spring-cloud-skipper#857]
When the apps are deleted from CF org/space outside of Skipper, upon querying for app package, we get the following errors.

```
   2019-03-25T10:42:05.68-0700 [RTR/0] OUT skipper-eee04cc2-29b2-453a-8d26-c9657cd48932.apps.menlopark.cf-app.com - [2019-03-25T17:42:05.662+0000] "DELETE /api/release/words/package HTTP/1.1" 500 0 320 "-" "Apache-HttpClient/4.5.7 (Java/1.8.0_192)" "35.222.34.90:54502" "10.0.4.23:61018" x_forwarded_for:"35.222.34.90" x_forwarded_proto:"https" vcap_request_id:"daebe68b-e3e6-4d4d-621e-5dc62f2cecf0" response_time:0.023702284 app_id:"c9853fda-5e75-4965-a7ae-eec021047597" app_index:"0" x_b3_traceid:"50250941eecc2fbc" x_b3_spanid:"50250941eecc2fbc" x_b3_parentspanid:"-"
   2019-03-25T10:42:05.68-0700 [RTR/0] OUT 
   2019-03-25T10:43:55.01-0700 [APP/PROC/WEB/0] OUT 2019-03-25 17:43:55.011  INFO 18 --- [nio-8080-exec-2] o.s.s.s.DefaultStateMachineService       : Acquiring machine with id words
   2019-03-25T10:43:55.01-0700 [APP/PROC/WEB/0] OUT 2019-03-25 17:43:55.012  INFO 18 --- [nio-8080-exec-2] o.s.s.s.DefaultStateMachineService       : Getting new machine from factory with id words
   2019-03-25T10:43:55.02-0700 [APP/PROC/WEB/0] OUT 2019-03-25 17:43:55.026 ERROR 18 --- [nio-8080-exec-2] o.s.s.s.DefaultStateMachineService       : Error handling context
   2019-03-25T10:43:55.02-0700 [APP/PROC/WEB/0] OUT com.esotericsoftware.kryo.KryoException: Buffer underflow.
   2019-03-25T10:43:55.02-0700 [APP/PROC/WEB/0] OUT     at com.esotericsoftware.kryo.io.Input.require(Input.java:199) ~[kryo-shaded-4.0.2.jar!/:na]
   2019-03-25T10:43:55.02-0700 [APP/PROC/WEB/0] OUT     at com.esotericsoftware.kryo.io.Input.readVarInt(Input.java:373) ~[kryo-shaded-4.0.2.jar!/:na]
   2019-03-25T10:43:55.02-0700 [APP/PROC/WEB/0] OUT     at com.esotericsoftware.kryo.util.DefaultClassResolver.readClass(DefaultClassResolver.java:127) 
```

**Comment by jvalkeal** [comment]
I'm a little confused by `querying for app package` what it actually means. I didn't get no errors if I removed those apps and then poked around.

**Comment by sabbyanandan** [comment]
@jvalkeal is working on a fix in State Machine, which will improve the overall state transition experience, so it might help the Skipper workflows, too.

**Comment by jvalkeal** [comment]
Fix is done with this https://github.com/spring-projects/spring-statemachine/issues/734

**Comment by jvalkeal** [comment]
Statemachine has been updated, so hopefully this if fixed.
