### ISSUE TITLE
Wrong kubernetes service account being used

### ISSUE THREAD

**Issue by shoreflyer** [spring-cloud/spring-cloud-skipper#872]
I've used a custom helm chart based on the official stable/spring-cloud-data-flow chart.
Main difference is no dependencies automatically installed.

The issue at hand is that it seems skipper ignores the role that is created as part of the chart.
Where spring-cloud-data-server picks up the correct one, in this case `system:serviceaccount:staging:sandbox-scdf-data-flow`, skipper on the other hand uses `system:serviceaccount:staging:default`. As I am using namespaces the error looks something like this:
```
2019-05-08 15:59:44.504  WARN 1 --- [           main] o.s.cloud.kubernetes.StandardPodUtils    : Failed to get pod with name:[sandbox-scdf-data-flow-skipper-649f8594d4-x6mww]. You should look into this if things aren't working as you expe
ct. Are you missing serviceaccount permissions?

io.fabric8.kubernetes.client.KubernetesClientException: Failure executing: GET at: https://10.100.0.1/api/v1/namespaces/staging/pods/sandbox-scdf-data-flow-skipper-649f8594d4-x6mww. Message: Forbidden!Configured service account doesn't ha
ve access. Service account may have been revoked. pods "sandbox-scdf-data-flow-skipper-649f8594d4-x6mww" is forbidden: User "system:serviceaccount:staging:default" cannot get pods in the namespace "staging".
        at io.fabric8.kubernetes.client.dsl.base.OperationSupport.requestFailure(OperationSupport.java:472) ~[kubernetes-client-4.0.4.jar!/:na]
        at io.fabric8.kubernetes.client.dsl.base.OperationSupport.assertResponseCode(OperationSupport.java:409) ~[kubernetes-client-4.0.4.jar!/:na]
        at io.fabric8.kubernetes.client.dsl.base.OperationSupport.handleResponse(OperationSupport.java:381) ~[kubernetes-client-4.0.4.jar!/:na]
        at io.fabric8.kubernetes.client.dsl.base.OperationSupport.handleResponse(OperationSupport.java:344) ~[kubernetes-client-4.0.4.jar!/:na]
        at io.fabric8.kubernetes.client.dsl.base.OperationSupport.handleGet(OperationSupport.java:313) ~[kubernetes-client-4.0.4.jar!/:na]
        at io.fabric8.kubernetes.client.dsl.base.OperationSupport.handleGet(OperationSupport.java:296) ~[kubernetes-client-4.0.4.jar!/:na]
        at io.fabric8.kubernetes.client.dsl.base.BaseOperation.handleGet(BaseOperation.java:794) ~[kubernetes-client-4.0.4.jar!/:na]
        at io.fabric8.kubernetes.client.dsl.base.BaseOperation.getMandatory(BaseOperation.java:210) ~[kubernetes-client-4.0.4.jar!/:na]
        at io.fabric8.kubernetes.client.dsl.base.BaseOperation.get(BaseOperation.java:177) ~[kubernetes-client-4.0.4.jar!/:na]
        at org.springframework.cloud.kubernetes.StandardPodUtils.internalGetPod(StandardPodUtils.java:62) [spring-cloud-kubernetes-core-1.0.0.RELEASE.jar!/:1.0.0.RELEASE]
        at org.springframework.cloud.kubernetes.StandardPodUtils.lambda$new$0(StandardPodUtils.java:46) [spring-cloud-kubernetes-core-1.0.0.RELEASE.jar!/:1.0.0.RELEASE]
        at org.springframework.cloud.kubernetes.LazilyInstantiate.swapper(LazilyInstantiate.java:41) ~[spring-cloud-kubernetes-core-1.0.0.RELEASE.jar!/:1.0.0.RELEASE]
        at org.springframework.cloud.kubernetes.LazilyInstantiate.lambda$new$0(LazilyInstantiate.java:34) ~[spring-cloud-kubernetes-core-1.0.0.RELEASE.jar!/:1.0.0.RELEASE]
        at org.springframework.cloud.kubernetes.LazilyInstantiate.get(LazilyInstantiate.java:29) ~[spring-cloud-kubernetes-core-1.0.0.RELEASE.jar!/:1.0.0.RELEASE]
        at org.springframework.cloud.kubernetes.StandardPodUtils.isInsideKubernetes(StandardPodUtils.java:56) [spring-cloud-kubernetes-core-1.0.0.RELEASE.jar!/:1.0.0.RELEASE]
        at org.springframework.cloud.kubernetes.profile.KubernetesProfileApplicationListener.addKubernetesProfile(KubernetesProfileApplicationListener.java:52) ~[spring-cloud-kubernetes-core-1.0.0.RELEASE.jar!/:1.0.0.RELEASE]
        at org.springframework.cloud.kubernetes.profile.KubernetesApplicationContextInitializer.initialize(KubernetesApplicationContextInitializer.java:57) ~[spring-cloud-kubernetes-core-1.0.0.RELEASE.jar!/:1.0.0.RELEASE]
        at org.springframework.boot.SpringApplication.applyInitializers(SpringApplication.java:649) ~[spring-boot-2.1.2.RELEASE.jar!/:2.1.2.RELEASE]
        at org.springframework.boot.SpringApplication.prepareContext(SpringApplication.java:373) ~[spring-boot-2.1.2.RELEASE.jar!/:2.1.2.RELEASE]
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:314) ~[spring-boot-2.1.2.RELEASE.jar!/:2.1.2.RELEASE]
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:1260) ~[spring-boot-2.1.2.RELEASE.jar!/:2.1.2.RELEASE]
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:1248) ~[spring-boot-2.1.2.RELEASE.jar!/:2.1.2.RELEASE]
        at org.springframework.cloud.skipper.server.app.SkipperServerApplication.main(SkipperServerApplication.java:48) ~[classes!/:2.0.0.RELEASE]
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_192]
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:1.8.0_192]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_192]
        at java.lang.reflect.Method.invoke(Method.java:498) ~[na:1.8.0_192]
        at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:48) ~[spring-cloud-skipper-server.jar:2.0.0.RELEASE]
        at org.springframework.boot.loader.Launcher.launch(Launcher.java:87) ~[spring-cloud-skipper-server.jar:2.0.0.RELEASE]
        at org.springframework.boot.loader.Launcher.launch(Launcher.java:50) ~[spring-cloud-skipper-server.jar:2.0.0.RELEASE]
        at org.springframework.boot.loader.JarLauncher.main(JarLauncher.java:51) ~[spring-cloud-skipper-server.jar:2.0.0.RELEASE]
```

Is there a way to instruct skipper to use the proper service account?

Skipper version: 2.0.0.RELEASE
SCDF server version: 2.0.1.RELEASE
As taken from the values file from the official helm chart...

**Comment by sabbyanandan** [comment]
Thanks for the report, @shoreflyer. Could you also update the description with versions in use?

**Comment by chrisjs** [comment]
@shoreflyer what does your `stable/spring-cloud-data-flow/templates/skipper-deployment.yaml` show for `serviceAccountName` ?

out of the box, both SCDF and Skipper use:

`serviceAccountName: {{ template "scdf.serviceAccountName" . }}`

**Comment by shoreflyer** [comment]
@chrisjs that is what I thought too, but it seems data-flow server uses the correct one and skipper somehow doesn't...
My values file has the following:
```
# Default values for spring-cloud-data-flow.
rbac:
  # Specifies whether RBAC resources should be created
  create: true

serviceAccount:
  # Specifies whether a service account should be created
  create: true
  # The name of the service account to use.
  # If not set and create is true, a name is generated using the serviceAccountName template
  name:

```

**Comment by shoreflyer** [comment]
<insert-face-palm> User error folks. My bad!
My skipper deployment had a missing  `serviceAccountName: {{ template "scdf.serviceAccountName" . }}` definition!
