### ISSUE TITLE
Can't run `mvnw clean install` 

### ISSUE THREAD

**Issue by xetra11** [spring-cloud/spring-cloud-skipper#928]
I'd like to create a pull request and therefore checked out the repo. Unfortunately I was not able to run `./mvnw clean install` for the project on my Arch Linux.

Here is the log extract:

```
[INFO] Reactor Summary for Spring Cloud Skipper 2.2.0.BUILD-SNAPSHOT:
[INFO] 
[INFO] Spring Cloud Skipper ............................... SUCCESS [  1.379 s]
[INFO] Spring Cloud Skipper :: Skipper .................... FAILURE [  3.040 s]
[INFO] Spring Cloud Skipper :: Server Core ................ SKIPPED
[INFO] Spring Cloud Skipper :: Kubernetes Platform ........ SKIPPED
[INFO] Spring Cloud Skipper :: CloudFoundry Platform ...... SKIPPED
[INFO] Spring Cloud Skipper :: Autoconfigure .............. SKIPPED
[INFO] Spring Cloud Skipper :: Server ..................... SKIPPED
[INFO] Spring Cloud Skipper :: Client ..................... SKIPPED
[INFO] Spring Cloud Skipper :: Shell Commands ............. SKIPPED
[INFO] Spring Cloud Skipper :: Shell ...................... SKIPPED
[INFO] Spring Cloud Skipper :: Docs ....................... SKIPPED
[INFO] Spring Cloud Skipper :: Dependencies ............... SKIPPED
[INFO] Spring Cloud Starter :: Skipper Server ............. SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  4.879 s
[INFO] Finished at: 2019-11-22T10:25:52+01:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-surefire-plugin:2.20:test (default-test) on project spring-cloud-skipper: There are test failures.
[ERROR] 
[ERROR] Please refer to /home/xetra11/workspace/development/github/spring-cloud-skipper/spring-cloud-skipper/target/surefire-reports for the individual test results.
[ERROR] Please refer to dump files (if any exist) [date]-jvmRun[N].dump, [date].dumpstream and [date]-jvmRun[N].dumpstream.
[ERROR] The forked VM terminated without properly saying goodbye. VM crash or System.exit called?
[ERROR] Command was /bin/sh -c cd /home/xetra11/workspace/development/github/spring-cloud-skipper/spring-cloud-skipper && /usr/lib/jvm/java-12-openjdk/bin/java -javaagent:/home/xetra11/.m2/repository/org/jacoco/org.jacoco.agent/0.7.9/org.jacoco.agent-0.7.9-runtime.jar=destfile=/home/xetra11/workspace/development/github/spring-cloud-skipper/spring-cloud-skipper/target/jacoco.exec -jar /home/xetra11/workspace/development/github/spring-cloud-skipper/spring-cloud-skipper/target/surefire/surefirebooter13114787567084339003.jar /home/xetra11/workspace/development/github/spring-cloud-skipper/spring-cloud-skipper/target/surefire 2019-11-22T10-25-51_198-jvmRun1 surefire3714663412285317582tmp surefire_01776386292435030935tmp
[ERROR] Error occurred in starting fork, check output in log
[ERROR] Process Exit Code: 134
[ERROR] org.apache.maven.surefire.booter.SurefireBooterForkException: The forked VM terminated without properly saying goodbye. VM crash or System.exit called?
[ERROR] Command was /bin/sh -c cd /home/xetra11/workspace/development/github/spring-cloud-skipper/spring-cloud-skipper && /usr/lib/jvm/java-12-openjdk/bin/java -javaagent:/home/xetra11/.m2/repository/org/jacoco/org.jacoco.agent/0.7.9/org.jacoco.agent-0.7.9-runtime.jar=destfile=/home/xetra11/workspace/development/github/spring-cloud-skipper/spring-cloud-skipper/target/jacoco.exec -jar /home/xetra11/workspace/development/github/spring-cloud-skipper/spring-cloud-skipper/target/surefire/surefirebooter13114787567084339003.jar /home/xetra11/workspace/development/github/spring-cloud-skipper/spring-cloud-skipper/target/surefire 2019-11-22T10-25-51_198-jvmRun1 surefire3714663412285317582tmp surefire_01776386292435030935tmp
[ERROR] Error occurred in starting fork, check output in log
[ERROR] Process Exit Code: 134
[ERROR]         at org.apache.maven.plugin.surefire.booterclient.ForkStarter.fork(ForkStarter.java:679)
[ERROR]         at org.apache.maven.plugin.surefire.booterclient.ForkStarter.fork(ForkStarter.java:533)
[ERROR]         at org.apache.maven.plugin.surefire.booterclient.ForkStarter.run(ForkStarter.java:279)
[ERROR]         at org.apache.maven.plugin.surefire.booterclient.ForkStarter.run(ForkStarter.java:243)
[ERROR]         at org.apache.maven.plugin.surefire.AbstractSurefireMojo.executeProvider(AbstractSurefireMojo.java:1077)
[ERROR]         at org.apache.maven.plugin.surefire.AbstractSurefireMojo.executeAfterPreconditionsChecked(AbstractSurefireMojo.java:907)
[ERROR]         at org.apache.maven.plugin.surefire.AbstractSurefireMojo.execute(AbstractSurefireMojo.java:785)
[ERROR]         at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:137)
[ERROR]         at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:210)
[ERROR]         at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:156)
[ERROR]         at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:148)
[ERROR]         at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:117)
[ERROR]         at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:81)
[ERROR]         at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:56)
[ERROR]         at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:128)
[ERROR]         at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:305)
[ERROR]         at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:192)
[ERROR]         at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:105)
[ERROR]         at org.apache.maven.cli.MavenCli.execute(MavenCli.java:956)
[ERROR]         at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:288)
[ERROR]         at org.apache.maven.cli.MavenCli.main(MavenCli.java:192)
[ERROR]         at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[ERROR]         at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[ERROR]         at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[ERROR]         at java.base/java.lang.reflect.Method.invoke(Method.java:567)
[ERROR]         at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)
[ERROR]         at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)
[ERROR]         at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)
[ERROR]         at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)
[ERROR]         at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[ERROR]         at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[ERROR]         at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[ERROR]         at java.base/java.lang.reflect.Method.invoke(Method.java:567)
[ERROR]         at org.apache.maven.wrapper.BootstrapMainStarter.start(BootstrapMainStarter.java:39)
[ERROR]         at org.apache.maven.wrapper.WrapperExecutor.execute(WrapperExecutor.java:122)
[ERROR]         at org.apache.maven.wrapper.MavenWrapperMain.main(MavenWrapperMain.java:50)
[ERROR] 
[ERROR] -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException
[ERROR] 
[ERROR] After correcting the problems, you can resume the build with the command
[ERROR]   mvn <goals> -rf :spring-cloud-skipper
```

**Comment by sabbyanandan** [comment]
@xetra11: Apologies for the delayed response. Somehow, we didn't see this sooner. If you continue to see the problem, please leave a comment here. We can help review.

**Comment by wankang189** [comment]
> @xetra11：对延迟响应表示歉意。不知何故，我们没有早点看到这一点。如果您仍然看到问题，请在此处发表评论。我们可以帮助审核。

How was it solved?

**Comment by xetra11** [comment]
@wankang189 
Haven't took a look into this for ages. I am sorry

**Comment by sabbyanandan** [comment]
Closing due to no activity.
