### ISSUE TITLE
Analyze the behavior of multiple instances of Skipper server

### ISSUE THREAD

**Issue by ilayaperumalg** [spring-cloud/spring-cloud-skipper#965]
This spike involves verifying the state of deployed applications when Skipper server upon restart and failover.

**Comment by ilayaperumalg** [comment]
When the skipper server re-starts, I see the following exception on deleting an existing installation:

```
2020-07-28 02:32:39.362 ERROR 1 --- [eTaskExecutor-3] o.s.c.s.server.statemachine.ErrorAction  : Going through error state DefaultStateContext [stage=STATE_ENTRY, message=GenericMessage [payload=DELETE, headers={RELEASE_DELETE_PROPERTIES=DeleteProperties{deletePackage=true}, RELEASE_NAME=s1, id=4ed80006-8e02-9bd1-3b2a-17da1088f0f3, timestamp=1595903559240}], messageHeaders={RELEASE_DELETE_PROPERTIES=DeleteProperties{deletePackage=true}, RELEASE_NAME=s1, id=4ed80006-8e02-9bd1-3b2a-17da1088f0f3, timestamp=1595903559240}, extendedState=DefaultExtendedState [variables={RELEASE_DELETE_PROPERTIES=DeleteProperties{deletePackage=true}, RELEASE_NAME=s1, ERROR=org.springframework.cloud.skipper.PackageDeleteException: Can not delete Package Metadata [s1:1.0.0] in Repository [local]. Not all releases of this package have the status DELETED. Active Releases [s1]}], transition=AbstractTransition [source=StateMachineState [getIds()=[DELETE, DELETE_DELETE], toString()=AbstractState [id=DELETE, pseudoState=null, deferred=[], entryActions=[], exitActions=[], stateActions=[], regions=[], submachine=DELETE_DELETE DELETE_EXIT  /  / uuid=e365c69c-d247-4c23-a4da-7d977e6a5092 / id=s1], getClass()=class org.springframework.statemachine.state.StateMachineState], target=ObjectState [getIds()=[ERROR_JUNCTION], getClass()=class org.springframework.statemachine.state.ObjectState, hashCode()=2071591841, toString()=AbstractState [id=ERROR_JUNCTION, pseudoState=org.springframework.statemachine.state.JunctionPseudoState@7ad407b8, deferred=[], entryActions=[], exitActions=[], stateActions=[], regions=[], submachine=null]], kind=EXTERNAL, guard=org.springframework.cloud.skipper.server.statemachine.StateMachineConfiguration$SkipperStateMachineFactoryConfig$$Lambda$1079/1438936769@3eff6846], stateMachine=DELETE DELETE_DELETE DELETE_EXIT UPGRADE UPGRADE_DEPLOY_TARGET_APPS_SUCCEED UPGRADE_DEPLOY_TARGET_APPS_FAILED UPGRADE_DEPLOY_TARGET_APPS UPGRADE_START UPGRADE_WAIT_TARGET_APPS UPGRADE_CANCEL UPGRADE_CHECK_TARGET_APPS UPGRADE_DELETE_SOURCE_APPS UPGRADE_CHECK_CHOICE UPGRADE_EXIT INSTALL INSTALL_INSTALL INSTALL_EXIT SCALE SCALE_SCALE SCALE_EXIT ERROR ROLLBACK ROLLBACK_START ROLLBACK_CHOICE ROLLBACK_EXIT ROLLBACK_EXIT_INSTALL ROLLBACK_EXIT_UPGRADE INITIAL ERROR_JUNCTION  / ERROR / uuid=26cf2871-c2b3-4e13-80d3-9db17d0cca85 / id=s1, source=null, target=null, sources=null, targets=null, exception=null] {}

org.springframework.cloud.skipper.PackageDeleteException: Can not delete Package Metadata [s1:1.0.0] in Repository [local]. Not all releases of this package have the status DELETED. Active Releases [s1]
	at org.springframework.cloud.skipper.server.service.PackageMetadataService.deleteIfAllReleasesDeleted(PackageMetadataService.java:134) ~[spring-cloud-skipper-server-core-2.5.0-SNAPSHOT.jar!/:2.5.0-SNAPSHOT]
	at org.springframework.cloud.skipper.server.service.PackageMetadataService$$FastClassBySpringCGLIB$$3321bb54.invoke(<generated>) ~[spring-cloud-skipper-server-core-2.5.0-SNAPSHOT.jar!/:2.5.0-SNAPSHOT]
	at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:218) ~[spring-core-5.2.6.RELEASE.jar!/:5.2.6.RELEASE]
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.invokeJoinpoint(CglibAopProxy.java:771) ~[spring-aop-5.2.6.RELEASE.jar!/:5.2.6.RELEASE]
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:163) ~[spring-aop-5.2.6.RELEASE.jar!/:5.2.6.RELEASE]
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:749) ~[spring-aop-5.2.6.RELEASE.jar!/:5.2.6.RELEASE]
	at org.springframework.transaction.interceptor.TransactionAspectSupport.invokeWithinTransaction(TransactionAspectSupport.java:366) ~[spring-tx-5.2.6.RELEASE.jar!/:5.2.6.RELEASE]
	at org.springframework.transaction.interceptor.TransactionInterceptor.invoke(TransactionInterceptor.java:118) ~[spring-tx-5.2.6.RELEASE.jar!/:5.2.6.RELEASE]
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186) ~[spring-aop-5.2.6.RELEASE.jar!/:5.2.6.RELEASE]
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:749) ~[spring-aop-5.2.6.RELEASE.jar!/:5.2.6.RELEASE]
	at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:691) ~[spring-aop-5.2.6.RELEASE.jar!/:5.2.6.RELEASE]
	at org.springframework.cloud.skipper.server.service.PackageMetadataService$$EnhancerBySpringCGLIB$$aa3ad099.deleteIfAllReleasesDeleted(<generated>) ~[spring-cloud-skipper-server-core-2.5.0-SNAPSHOT.jar!/:2.5.0-SNAPSHOT]
	at org.springframework.cloud.skipper.server.service.ReleaseService.delete(ReleaseService.java:237) ~[spring-cloud-skipper-server-core-2.5.0-SNAPSHOT.jar!/:2.5.0-SNAPSHOT]
	at org.springframework.cloud.skipper.server.service.ReleaseService$$FastClassBySpringCGLIB$$f1c5f0a2.invoke(<generated>) ~[spring-cloud-skipper-server-core-2.5.0-SNAPSHOT.jar!/:2.5.0-SNAPSHOT]
	at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:218) ~[spring-core-5.2.6.RELEASE.jar!/:5.2.6.RELEASE]
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.invokeJoinpoint(CglibAopProxy.java:771) ~[spring-aop-5.2.6.RELEASE.jar!/:5.2.6.RELEASE]
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:163) ~[spring-aop-5.2.6.RELEASE.jar!/:5.2.6.RELEASE]
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:749) ~[spring-aop-5.2.6.RELEASE.jar!/:5.2.6.RELEASE]
	at org.springframework.transaction.interceptor.TransactionAspectSupport.invokeWithinTransaction(TransactionAspectSupport.java:366) ~[spring-tx-5.2.6.RELEASE.jar!/:5.2.6.RELEASE]
	at org.springframework.transaction.interceptor.TransactionInterceptor.invoke(TransactionInterceptor.java:118) ~[spring-tx-5.2.6.RELEASE.jar!/:5.2.6.RELEASE]
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186) ~[spring-aop-5.2.6.RELEASE.jar!/:5.2.6.RELEASE]
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:749) ~[spring-aop-5.2.6.RELEASE.jar!/:5.2.6.RELEASE]
	at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:691) ~[spring-aop-5.2.6.RELEASE.jar!/:5.2.6.RELEASE]
	at org.springframework.cloud.skipper.server.service.ReleaseService$$EnhancerBySpringCGLIB$$59543143.delete(<generated>) ~[spring-cloud-skipper-server-core-2.5.0-SNAPSHOT.jar!/:2.5.0-SNAPSHOT]
	at org.springframework.cloud.skipper.server.statemachine.DeleteDeleteAction.executeInternal(DeleteDeleteAction.java:64) ~[spring-cloud-skipper-server-core-2.5.0-SNAPSHOT.jar!/:2.5.0-SNAPSHOT]
	at org.springframework.cloud.skipper.server.statemachine.AbstractAction.execute(AbstractAction.java:41) ~[spring-cloud-skipper-server-core-2.5.0-SNAPSHOT.jar!/:2.5.0-SNAPSHOT]
	at org.springframework.statemachine.state.AbstractState.executeAction(AbstractState.java:496) ~[spring-statemachine-core-2.2.0.RELEASE.jar!/:2.2.0.RELEASE]
	at org.springframework.statemachine.state.ObjectState.entry(ObjectState.java:158) ~[spring-statemachine-core-2.2.0.RELEASE.jar!/:2.2.0.RELEASE]
	at org.springframework.statemachine.support.AbstractStateMachine.entryToState(AbstractStateMachine.java:1322) [spring-statemachine-core-2.2.0.RELEASE.jar!/:2.2.0.RELEASE]
	at org.springframework.statemachine.support.AbstractStateMachine.entryToState(AbstractStateMachine.java:1263) [spring-statemachine-core-2.2.0.RELEASE.jar!/:2.2.0.RELEASE]
	at org.springframework.statemachine.support.AbstractStateMachine.setCurrentStateInternal(AbstractStateMachine.java:1059) [spring-statemachine-core-2.2.0.RELEASE.jar!/:2.2.0.RELEASE]
	at org.springframework.statemachine.support.AbstractStateMachine.setCurrentState(AbstractStateMachine.java:1033) [spring-statemachine-core-2.2.0.RELEASE.jar!/:2.2.0.RELEASE]
	at org.springframework.statemachine.support.AbstractStateMachine.switchToState(AbstractStateMachine.java:926) [spring-statemachine-core-2.2.0.RELEASE.jar!/:2.2.0.RELEASE]
	at org.springframework.statemachine.support.AbstractStateMachine.access$500(AbstractStateMachine.java:82) [spring-statemachine-core-2.2.0.RELEASE.jar!/:2.2.0.RELEASE]
	at org.springframework.statemachine.support.AbstractStateMachine$3.transit(AbstractStateMachine.java:334) [spring-statemachine-core-2.2.0.RELEASE.jar!/:2.2.0.RELEASE]
	at org.springframework.statemachine.support.DefaultStateMachineExecutor.handleInitialTrans(DefaultStateMachineExecutor.java:302) [spring-statemachine-core-2.2.0.RELEASE.jar!/:2.2.0.RELEASE]
	at org.springframework.statemachine.support.DefaultStateMachineExecutor.processTriggerQueue(DefaultStateMachineExecutor.java:398) [spring-statemachine-core-2.2.0.RELEASE.jar!/:2.2.0.RELEASE]
	at org.springframework.statemachine.support.DefaultStateMachineExecutor.access$200(DefaultStateMachineExecutor.java:64) [spring-statemachine-core-2.2.0.RELEASE.jar!/:2.2.0.RELEASE]
	at org.springframework.statemachine.support.DefaultStateMachineExecutor$1.run(DefaultStateMachineExecutor.java:330) [spring-statemachine-core-2.2.0.RELEASE.jar!/:2.2.0.RELEASE]
	at org.springframework.core.task.SyncTaskExecutor.execute(SyncTaskExecutor.java:50) [spring-core-5.2.6.RELEASE.jar!/:5.2.6.RELEASE]
	at org.springframework.statemachine.support.DefaultStateMachineExecutor.scheduleEventQueueProcessing(DefaultStateMachineExecutor.java:353) [spring-statemachine-core-2.2.0.RELEASE.jar!/:2.2.0.RELEASE]
	at org.springframework.statemachine.support.DefaultStateMachineExecutor.execute(DefaultStateMachineExecutor.java:162) [spring-statemachine-core-2.2.0.RELEASE.jar!/:2.2.0.RELEASE]
	at org.springframework.statemachine.support.DefaultStateMachineExecutor.doStart(DefaultStateMachineExecutor.java:174) [spring-statemachine-core-2.2.0.RELEASE.jar!/:2.2.0.RELEASE]
	at org.springframework.statemachine.support.LifecycleObjectSupport.start(LifecycleObjectSupport.java:120) [spring-statemachine-core-2.2.0.RELEASE.jar!/:2.2.0.RELEASE]
	at org.springframework.statemachine.support.AbstractStateMachine.doStart(AbstractStateMachine.java:418) [spring-statemachine-core-2.2.0.RELEASE.jar!/:2.2.0.RELEASE]
	at org.springframework.statemachine.support.LifecycleObjectSupport.start(LifecycleObjectSupport.java:120) [spring-statemachine-core-2.2.0.RELEASE.jar!/:2.2.0.RELEASE]
	at org.springframework.statemachine.state.StateMachineState.entry(StateMachineState.java:236) [spring-statemachine-core-2.2.0.RELEASE.jar!/:2.2.0.RELEASE]
	at org.springframework.statemachine.support.AbstractStateMachine.entryToState(AbstractStateMachine.java:1322) [spring-statemachine-core-2.2.0.RELEASE.jar!/:2.2.0.RELEASE]
	at org.springframework.statemachine.support.AbstractStateMachine.entryToState(AbstractStateMachine.java:1263) [spring-statemachine-core-2.2.0.RELEASE.jar!/:2.2.0.RELEASE]
	at org.springframework.statemachine.support.AbstractStateMachine.setCurrentStateInternal(AbstractStateMachine.java:1059) [spring-statemachine-core-2.2.0.RELEASE.jar!/:2.2.0.RELEASE]
	at org.springframework.statemachine.support.AbstractStateMachine.setCurrentState(AbstractStateMachine.java:1033) [spring-statemachine-core-2.2.0.RELEASE.jar!/:2.2.0.RELEASE]
	at org.springframework.statemachine.support.AbstractStateMachine.switchToState(AbstractStateMachine.java:926) [spring-statemachine-core-2.2.0.RELEASE.jar!/:2.2.0.RELEASE]
	at org.springframework.statemachine.support.AbstractStateMachine.access$500(AbstractStateMachine.java:82) [spring-statemachine-core-2.2.0.RELEASE.jar!/:2.2.0.RELEASE]
	at org.springframework.statemachine.support.AbstractStateMachine$3.transit(AbstractStateMachine.java:337) [spring-statemachine-core-2.2.0.RELEASE.jar!/:2.2.0.RELEASE]
	at org.springframework.statemachine.support.DefaultStateMachineExecutor.handleTriggerTrans(DefaultStateMachineExecutor.java:287) [spring-statemachine-core-2.2.0.RELEASE.jar!/:2.2.0.RELEASE]
	at org.springframework.statemachine.support.DefaultStateMachineExecutor.handleTriggerTrans(DefaultStateMachineExecutor.java:210) [spring-statemachine-core-2.2.0.RELEASE.jar!/:2.2.0.RELEASE]
	at org.springframework.statemachine.support.DefaultStateMachineExecutor.processTriggerQueue(DefaultStateMachineExecutor.java:450) [spring-statemachine-core-2.2.0.RELEASE.jar!/:2.2.0.RELEASE]
	at org.springframework.statemachine.support.DefaultStateMachineExecutor.access$200(DefaultStateMachineExecutor.java:64) [spring-statemachine-core-2.2.0.RELEASE.jar!/:2.2.0.RELEASE]
	at org.springframework.statemachine.support.DefaultStateMachineExecutor$1.run(DefaultStateMachineExecutor.java:324) [spring-statemachine-core-2.2.0.RELEASE.jar!/:2.2.0.RELEASE]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [na:1.8.0_192]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [na:1.8.0_192]
	at java.lang.Thread.run(Thread.java:748) [na:1.8.0_192]
```

**Comment by sabbyanandan** [comment]
Duplicates https://github.com/spring-cloud/spring-cloud-skipper/issues/975.
